### PR TITLE
Assignment-1

### PR DESCRIPTION
**Pull request by Daya709**
## Checklist
- [ ] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by tianyi21 — CHANGES_REQUESTED** [review]
Hi Dayaram! 

Thank you for completing and submitting your ADS A1:
* You implemented an algorithm to identify the missing number in a provided list.
* You demonstrated how you approached the problem and analyzed your solution.
* I'm only marking the assigned question, i.e., Q3

I noticed the following issue(s) with your submission. I would appreciate it if you could provide a short explanation to each of the following points and revise your submission to address these issue(s):
* I noticed that you implemented two versions. Can you explain the connection between them? Is the second version an improved idea from the first one? If so, what is the advantage of the second version?
* In both versions, when the input is `[5,0,1]`, i.e., Ex2, what is the desired output and what would be the output of your algorithm, respectively?
* In your second version, could you elaborate on why you compute the absolute value with `abs()`?
* You stated that the space complexity is $O(1)$. In your first version, you create a new set `ideal_set = set(range(n + 1))` and in your second version, you created a list `missing = []`. Could you re-consider the space complexity in both cases? Are they still $O(1)$?
* You mentioned in your alternative approach that step 4 will be edge case handling. Could you explain what will be the edge case?

Thanks,
Tianyi [LS]

**Comment by tianyi21** [comment]
Hi Dayaram. Please kindly remember to address the issues I mentioned above. Thank you.

**Comment by Daya709** [comment]
Hi,
I apologize for the delay! I am currently having unplanned worload, I am
almost working 4 almost 4 hours more than regular hours and 12 hours during
weekend. I know these are not the excuses but just letting you know that I
might be late.

Thank you for your understanding!

Regards,
Dayaram

**Comment by Daya709** [comment]
Hi Tiyani
Please find my response belo

I noticed that you implemented two versions. Can you explain the connection between them? Is the second version an improved idea from the first one? If so, what is the advantage of the second version?
-- There is no connection between the first and second versions of the code. It demonstrates only two different logic and a second has worse time and space complexity than the first code.
In both versions, when the input is [5,0,1], i.e., Ex2, what is the desired output and what would be the output of your algorithm, respectively?
-- Code has been improved to get the correct output for the [5,0,1]. Thank you for pointing this out. 
In your second version, could you elaborate on why you compute the absolute value with abs()?
-- this has been removed in this version
You stated that the space complexity is 
O
(
1
)
. In your first version, you create a new set ideal_set = set(range(n + 1)) and in your second version, you created a list missing = []. Could you re-consider the space complexity in both cases? Are they still 
O
(
1
)
-- I believe time and space complexity remain the same for range( n+1).
You mentioned in your alternative approach that step 4 will be edge case handling. Could you explain what will be the edge case?
-- This has been removed in the second version.
Thanks,
Dayaram

**Comment by tianyi21** [comment]
Hi Dayaram!

Thank you for revising and resubmitting your ADS A1. Please feel free to explore a few more efficient solutions [here](https://gist.github.com/meilinz/c208fa8f56fcb7e3340174e5972458b9).

All your ADS assignments have been completed. In future modules, please only merge your PR after it is **approved by** the learning support. Thank you for your participation, and I wish you all the success in your future endeavours.

Thanks,
Tianyi [LS]

**Comment by tianyi21** [comment]
Hi Dayaram!

Thank you for revising and resubmitting your ADS A1. Please feel free to explore a few more efficient solutions [here](https://gist.github.com/meilinz/c208fa8f56fcb7e3340174e5972458b9).

All your ADS assignments have been completed. In future modules, please merge your PR **after it is approved** by the learning support. Thank you for your participation, and I wish you all the success in your future endeavours.

Thanks,
Tianyi [LS]

**Comment by Daya709** [comment]
HI Tianyi,
Thank you so much for your patience and for allowing me more time!

I will follow the link for the more efficient code.

Regards,
Dayaram

**Pull request merged**
